# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# compile CXX with /usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -I/home/sung/Downloads/libpointmatcher-1.2.4/contrib/yaml-cpp-pm/include -I/home/sung/Downloads/libpointmatcher-1.2.4 -I/home/sung/Downloads/libpointmatcher-1.2.4/pointmatcher -I/home/sung/Downloads/libpointmatcher-1.2.4/pointmatcher/DataPointsFilters -I/home/sung/Downloads/libpointmatcher-1.2.4/pointmatcher/DataPointsFilters/utils -isystem /usr/local/include/eigen3

CXX_FLAGS = -O3 -DNDEBUG   -fPIC -O3 -Wall -std=gnu++11

